// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef fluid_h
#define fluid_h
#include <FL/Fl.H>
#include "globals.h"
#include "button_mouse_click.h"
extern fluid_wnd *wnd_fluid; 
#include <FL/Fl_Button.H>
extern Fl_Button *bt_button0;
#include <FL/Fl_Input.H>
extern Fl_Input *fi_remaining_tim0;
extern Fl_Button *bt_start0;
extern Fl_Input *fi_cmd0;
extern Fl_Button *bt_test0;
extern Fl_Button *bt_num0;
extern Fl_Button *bt_num7;
extern Fl_Button *bt_num8;
extern Fl_Button *bt_num9;
extern Fl_Button *bt_num4;
extern Fl_Button *bt_num5;
extern Fl_Button *bt_num6;
extern Fl_Button *bt_num1;
extern Fl_Button *bt_num2;
extern Fl_Button *bt_num3;
extern Fl_Button *bt_clr;
extern Fl_Button *bt_reset0;
extern Fl_Input *fi_interval_tim0;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *ck_cycle0;
extern Fl_Check_Button *ck_beep0;
extern Fl_Check_Button *ck_wintop0;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *bt_sel0;
extern Fl_Round_Button *bt_sel1;
extern Fl_Round_Button *bt_sel2;
extern Fl_Input *fi_beeps0;
extern Fl_Input *fi_pitch0;
extern Fl_Button *bt_load;
extern Fl_Button *bt_save;
extern button_mouse_click *bt_dur15;
extern button_mouse_click *bt_dur30;
extern button_mouse_click *bt_dur5;
extern button_mouse_click *bt_dur1;
extern button_mouse_click *bt_dur45;
extern button_mouse_click *bt_dur60;
extern button_mouse_click *bt_dur10;
extern Fl_Check_Button *ck_cmd_on0;
extern button_mouse_click *bt_dur20;
extern Fl_Input *fi_remaining_tim1;
extern Fl_Button *bt_start1;
extern Fl_Input *fi_cmd1;
extern Fl_Button *bt_test1;
extern Fl_Button *bt_reset1;
extern Fl_Input *fi_interval_tim1;
extern Fl_Check_Button *ck_cycle1;
extern Fl_Check_Button *ck_beep1;
extern Fl_Check_Button *ck_wintop1;
extern Fl_Input *fi_beeps1;
extern Fl_Input *fi_pitch1;
extern Fl_Check_Button *ck_cmd_on1;
extern Fl_Input *fi_remaining_tim2;
extern Fl_Button *bt_start2;
extern Fl_Input *fi_cmd2;
extern Fl_Button *bt_test2;
extern Fl_Button *bt_reset2;
extern Fl_Input *fi_interval_tim2;
extern Fl_Check_Button *ck_cycle2;
extern Fl_Check_Button *ck_beep2;
extern Fl_Check_Button *ck_wintop2;
extern Fl_Input *fi_beeps2;
extern Fl_Input *fi_pitch2;
extern Fl_Check_Button *ck_cmd_on2;
extern Fl_Input *fi_time_now;
#include <FL/Fl_Box.H>
extern Fl_Box *bx_interval_eta0;
extern Fl_Box *bx_eta0;
extern Fl_Box *bx_interval_eta1;
extern Fl_Box *bx_eta1;
extern Fl_Box *bx_interval_eta2;
extern Fl_Box *bx_eta2;
extern Fl_Box *bx_ctrl_minus;
extern Fl_Button *bt_minus;
extern Fl_Button *bt_about;
extern Fl_Button *bt_trim_01;
extern Fl_Button *bt_trim01;
extern Fl_Button *bt_trim05;
extern Fl_Button *bt_trim_05;
extern Fl_Button *bt_trim_11;
extern Fl_Button *bt_trim11;
extern Fl_Button *bt_trim15;
extern Fl_Button *bt_trim_15;
extern Fl_Button *bt_trim_21;
extern Fl_Button *bt_trim21;
extern Fl_Button *bt_trim25;
extern Fl_Button *bt_trim_25;
fluid_wnd* make_fluid_window();
#endif
